"""
Figure 2 -- Three dynamic regimes of the deterministic skeleton.

Same model, same six trader types, three points in parameter space. The top row
shows the deviation from fundamental value over time; the bottom row shows the
corresponding phase portrait in the plane (x_{t-1}, x_t).

A stable cycle traces a finite set of points, a torus traces a closed loop, and
a chaotic attractor traces a fractal set. No random shock is involved in any of
the three: all of the irregularity in the right-hand column is generated by the
switching of traders between forecasting rules.
"""

from _common import FIGDIR, TABDIR, announce

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from bh1998 import calibration, simulate
from bh1998.analysis import detect_period, lyapunov_rosenstein
from bh1998.plotting import ACCENT, HILITE, MUTED, label_panel, save

REGIMES = [
    ("benchmark", "Stable cycle", r"$\beta=2,\ \varphi=0.2,\ \alpha_{\rm opt}=1.5$"),
    ("quasiperiodic", "Quasi-periodic", r"$\beta=20,\ \varphi=0.2,\ \alpha_{\rm opt}=1.5$"),
    ("chaotic", "Deterministic chaos", r"$\beta=10,\ \varphi=1.0,\ \alpha_{\rm opt}=0.3$"),
]


def main() -> None:
    fig, axes = plt.subplots(2, 3, figsize=(12.6, 6.4))
    rows = []

    for j, (key, title, subtitle) in enumerate(REGIMES):
        p, r = calibration(key, n_steps=12_000, burn_in=4_000)
        res = simulate(p, r).trimmed()
        x = res.x
        per = detect_period(x)
        lle = lyapunov_rosenstein(x)

        # --- top: time series ------------------------------------------
        ax = axes[0, j]
        win = 80
        ax.plot(x[:win], color=ACCENT, lw=1.0, marker="o", ms=2.4,
                markerfacecolor="white", markeredgewidth=0.7)
        ax.axhline(0, color=MUTED, lw=0.8, ls=":")
        ax.set_title(f"{title}\n{subtitle}", fontsize=10.5)
        ax.set_xlabel("Period $t$")
        if j == 0:
            ax.set_ylabel(r"Deviation $x_t$")
        label_panel(ax, f"({chr(97 + j)})")

        tag = f"period {per}" if per else "aperiodic"
        ax.text(
            0.975, 0.05, f"{tag}\n$\\lambda_{{\\max}} = {lle:+.3f}$",
            transform=ax.transAxes, ha="right", va="bottom", fontsize=9,
            color=HILITE if lle > 0.01 else "#555555",
            bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="#cccccc", lw=0.6),
        )

        # --- bottom: phase portrait ------------------------------------
        ax = axes[1, j]
        ms = 6.0 if per else 1.3
        alpha = 0.9 if per else 0.30
        ax.plot(
            x[:-1], x[1:], ".", ms=ms, alpha=alpha, color=ACCENT,
            rasterized=True,
        )
        lim = 1.12 * np.max(np.abs(x))
        ax.plot([-lim, lim], [-lim, lim], color=MUTED, lw=0.7, ls=":")
        ax.set_xlim(-lim, lim)
        ax.set_ylim(-lim, lim)
        ax.set_aspect("equal")
        ax.set_xlabel(r"$x_{t-1}$")
        if j == 0:
            ax.set_ylabel(r"$x_t$")
        label_panel(ax, f"({chr(100 + j)})")

        rows.append(
            {
                "Regime": title,
                "Period": per if per else "aperiodic",
                "Lyapunov": round(lle, 4),
                "Std. dev of x": round(float(np.std(x)), 4),
                "Range of x": round(float(np.ptp(x)), 4),
            }
        )

    fig.suptitle(
        "Three regimes of the same model: cycle, torus, chaos",
        fontsize=13, fontweight="bold", y=1.0,
    )
    fig.tight_layout()
    announce(save(fig, FIGDIR / "fig02_regimes.png").name)

    tab = pd.DataFrame(rows)
    tab.to_csv(TABDIR / "table_regimes.csv", index=False)
    print(tab.to_string(index=False))


if __name__ == "__main__":
    main()
